spring:
  application:
    name: excel-demo
  datasource:
    url: jdbc:mysql://localhost:3306/hhawking
    username: root
    password:
    tomcat:
      max-idle: 3
      initial-size: 1
      max-active: 5
      max-wait: 5000

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mapper/*.xml